name: 'deploy-to-acr'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
 
  deploy-to-acr:
    name: 'deploy-to-acr'
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: e-class-prod-rg
      ResourceGroupLocation: "southcentralus"
      AcrName: eclasstestacr
    environment: production
 
    steps:
 
    - uses: actions/checkout@v2
 
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
         
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/eclass-front:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/eclass-front:latest

